name: .NET

on:
  push:
    branches: [ "main"]
    paths:
      - "csharp/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "csharp/**"
env:
  SOLUTION_PATH: 'csharp/SemanticRelease.sln'
  PROJECT_PATH: 'csharp/LiftButton/LiftButton.csproj'
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}/output
  NUGET_PUSH_URL: ${{ secrets.NUGET_PUSH_URL }}
  NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore dependencies
        run: dotnet restore ${{ env.SOLUTION_PATH }}

      - name: Build
        run: dotnet build ${{ env.SOLUTION_PATH }} --no-restore

      - name: Test
        run: dotnet test ${{ env.SOLUTION_PATH }} --no-build --verbosity normal

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install dependencies
        working-directory: ./csharp
        run: npm install @semantic-release/changelog @semantic-release/git @semantic-release/exec

      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        working-directory: ./csharp
        run: npm audit signatures

      - name: Release
        id: release
        working-directory: ./csharp
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release

      - name: 'Publish NuGet package'
        if: ${{ steps.release.outputs.new_release_version }}
        run: |
          if [ -z "${{ secrets.NUGET_TOKEN }}" ] || [ -z "${{ secrets.NUGET_PUSH_URL }}" ]; then
            echo "::warning::NuGet secrets are missing. Skipping NuGet publish."
            exit 0
          fi
          dotnet clean ${{ env.SOLUTION_PATH }}
          dotnet pack ${{ env.PROJECT_PATH }} --configuration Release --include-symbols --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}
          dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}/*.nupkg -k ${{ secrets.NUGET_TOKEN }} -s ${{ env.NUGET_PUSH_URL }}
