name: .NET

on:
  push:
    branches: [ "main", "csharp" ]
    paths:
      - "csharp/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "csharp/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore csharp/SemanticRelease.sln

      - name: Build
        run: dotnet build csharp/SemanticRelease.sln --no-restore

      - name: Test
        run: dotnet test csharp/SemanticRelease.sln --no-build --verbosity normal
